

export const pageData = {
    genres: {
        1: 'Alternative',
        a: 'Alternative/College Rock',
        b: 'Alternative/Goth Rock',
        c: 'Alternative/Grunge',
        d: 'Alternative/Indie Rock',
        e: 'Alternative/New Wave',
        2: 'Blues',
        aa: 'Blues/Acoustic Blues',
        ab: 'Blues/Chicago Blues',
        ac: 'Blues/Classic Blues',
        ad: 'Blues/Contemporary Blues',
        ae: 'Blues/Country Blues',
        af: 'Blues/Delta Blues',
        ag: 'Blues/Electric Blues',
        3: 'Children\'s Music',
        ba: 'Children\'s Music/Lullabies',
        bb: 'Children\'s Music/Sing-Along',
        4: 'Country',
        ca: 'Country/Alternative Country',
        cb: 'Country/Americana',
        cc: 'Country/Bluegrass',
        cd: 'Country/Contemporary Bluegrass',
        ce: 'Country/Contemporary Country',
        cf: 'Country/Country Gospel',
        cg: 'Country/Honky Tonk',
        ch: 'Country/Outlaw Country',
        ci: 'Country/Traditional Bluegrass',
        cj: 'Country/Traditional Country',
        ck: 'Country/Urban Country',
        5: 'Dance',
        da: 'Dance/Breakbeat',
        db: 'Dance/Garage',
        dc: 'Dance/Hardcore',
        dd: 'Dance/House',
        de: 'Dance/Jungle/Drum\'n\'bass',
        df: 'Dance/Techno',
        dg: 'Dance/Trance',
        dh: 'Dance/Trap',
        6: 'Electronic',
        ea: 'Electronic/Ambient',
        eb: 'Electronic/Bass',
        ec: 'Electronic/Downtempo',
        ed: 'Electronic/Dubstep',
        ee: 'Electronic/Electronica',
        ef: 'Electronic/IDM/Experimental',
        eg: 'Electronic/Industrial',
        eh: 'Electronic/Levant Electronic',
        ei: 'Electronic/Maghreb Electronic',
        7: 'Folk',
        8: 'Hip-Hop/Rap',
        fa: 'Hip-Hop/Rap/Alternative Rap',
        fb: 'Hip-Hop/Rap/Dirty South',
        fc: 'Hip-Hop/Rap/East Coast Rap',
        fd: 'Hip-Hop/Rap/Gangsta Rap',
        fe: 'Hip-Hop/Rap/Hardcore Rap',
        ff: 'Hip-Hop/Rap/Hip-Hop',
        fg: 'Hip-Hop/Rap/Latin Rap',
        fh: 'Hip-Hop/Rap/Old School Rap',
        fi: 'Hip-Hop/Rap/Rap',
        fj: 'Hip-Hop/Rap/Underground Rap',
        fk: 'Hip-Hop/Rap/West Coast Rap',
        9: 'Holiday',
        ga: 'Holiday/Christmas',
        gb: 'Holiday/Easter',
        gc: 'Holiday/Thanksgiving',
        gd: 'Holiday/Traditional',
        10: 'Inspirational',
        11: 'Jazz',
        ha: 'Jazz/Avant-Garde Jazz',
        hb: 'Jazz/Big Band',
        hc: 'Jazz/Bop',
        hd: 'Jazz/Contemporary Jazz',
        he: 'Jazz/Cool',
        hf: 'Jazz/Crossover Jazz',
        hg: 'Jazz/Dixieland',
        hh: 'Jazz/Easy Listening',
        hi: 'Jazz/Hard Bop',
        hj: 'Jazz/Latin Jazz',
        hk: 'Jazz/Mainstream Jazz',
        hl: 'Jazz/Ragtime',
        hm: 'Jazz/Smooth Jazz',
        hn: 'Jazz/Trad Jazz',
        12: 'Latin',
        ia: 'Latin/Alternativo & Rock Latino',
        ib: 'Latin/Baladas y Boleros',
        ic: 'Latin/Contemporary Latin',
        id: 'Latin/Pop Latino',
        ie: 'Latin/Raices',
        if: 'Latin/Reggaeton y Hip-Hop',
        ig: 'Latin/Regional Mexicano',
        ih: 'Latin/Salsa y Tropical',
        13: 'New Age',
        ja: 'New Age/Meditation',
        jb: 'New Age/Travel',
        jc: 'New Age/Yoga',
        14: 'Pop',
        ka: 'Pop/Adult Contemporary',
        kb: 'Pop/Britpop',
        kc: 'Pop/Pop/Rock',
        kd: 'Pop/Singer/Songwriter',
        ke: 'Pop/Soft Rock',
        kf: 'Pop/Teen Pop',
        15: 'R&B/Soul',
        la: 'R&B/Soul/Contemporary R&B',
        lb: 'R&B/Soul/Disco',
        lc: 'R&B/Soul/Doo Wop',
        ld: 'R&B/Soul/Funk',
        le: 'R&B/Soul/Motown',
        lf: 'R&B/Soul/Neo-Soul',
        lg: 'R&B/Soul/Soul',
        16: 'Reggae',
        ma: 'Reggae/Dub',
        mb: 'Reggae/Lovers Rock',
        mc: 'Reggae/Modern Dancehall',
        md: 'Reggae/Roots Reggae',
        me: 'Reggae/Ska',
        17: 'Rock',
        na: 'Rock/Adult Alternative',
        nb: 'Rock/American Trad Rock',
        nc: 'Rock/Arena Rock',
        nd: 'Rock/Blues-Rock',
        ne: 'Rock/British Invasion',
        nf: 'Rock/Death Metal',
        ng: 'Rock/Death Metal/Black Metal',
        nh: 'Rock/Glam Rock',
        ni: 'Rock/Hair Metal',
        nj: 'Rock/Hard Rock',
        nk: 'Rock/Heavy Metal',
        nl: 'Rock/Jam Bands',
        nm: 'Rock/Prog-Rock/Art Rock',
        nn: 'Rock/Psychadelic',
        no: 'Rock/Rockabilly',
        np: 'Rock/Rock & Roll',
        nq: 'Rock/Roots Rock',
        nr: 'Rock/Southern Rock',
        ns: 'Rock/Surf',
        nt: 'Rock/Tex-Mex',
        18: 'Soundtrack',
        oa: 'Soundtrack/Foreign Cinema',
        ob: 'Soundtrack/Musicals',
        oc: 'Soundtrack/original Score',
        od: 'Soundtrack/TV Soundtrack',
        oe: 'Soundtrack/Video Game',
        19: 'Vocal',
        pa: 'Vocal/Standards',
        pb: 'Vocal/Traditional Pop',
        pc: 'Vocal/Vocal Jazz',
        pd: 'Vocal/Vocal Pop',
        20: 'World',
        qa: 'World/Afrobeats'
    },
    languages: {
        1: 'Afar',
        2: 'Afrikaans',
        3: 'Akan',
        4: 'Albanian',
        5: 'Amharic',
        6: 'Arabic',
        7: 'Aragonese',
        8: 'Armenian',
        9: 'Assamese',
        10: 'Avaric',
        11: 'Avestan',
        12: 'Aymara',
        13: 'Azerbaijani',
        14: 'Bambara',
        15: 'Bashkir',
        16: 'Basque',
        17: 'Belarusian',
        18: 'Bengali',
        19: 'Bhojpuri',
        20: 'Bislama',
        21: 'Bosnian',
        22: 'Breton',
        23: 'Bulgarian',
        24: 'Burmese',
        25: 'Cantonese',
        26: 'Catalan; Valencian',
        27: 'Central Khmer',
        28: 'Chamorro',
        29: 'Chechen',
        30: 'Chichewa',
        31: 'Chinese',
        32: 'Chinese; Mandarin Simplified',
        33: 'Chinese; Mandarin Traditional',
        34: 'Chuvash',
        35: 'Cornish',
        36: 'Corsican',
        37: 'Cree',
        38: 'Croatian',
        39: 'Czech',
        40: 'Danish',
        41: 'Divehi',
        42: 'Dutch',
        43: 'Dzongkha',
        44: 'English',
        45: 'Esperanto',
        46: 'Estonian',
        47: 'Ewe',
        48: 'Faroese',
        49: 'Fijian',
        50: 'Finnish',
        51: 'French',
        52: 'Fulah',
        53: 'Gaelic',
        54: 'Galician',
        55: 'Georgian',
        56: 'German',
        57: 'Greek, Modern',
        58: 'Guarani',
        59: 'Gujarati',
        60: 'Hausa',
        61: 'Hebrew',
        62: 'Herero',
        63: 'Hindi',
        64: 'Hiri Motu',
        65: 'Hungarian',
        66: 'Icelandic',
        67: 'Ido',
        68: 'Igbo',
        69: 'Indonesian',
        70: 'Interlingua',
        71: 'Interlingue',
        72: 'Inuktitut',
        73: 'Inupiaq',
        74: 'Irish',
        75: 'Italian',
        76: 'Japanese',
        77: 'Javanese',
        78: 'Kalaallisut',
        79: 'Kannada',
        80: 'Kanuri',
        81: 'Kashmiri',
        82: 'Kazakh',
        83: 'Kikuyu',
        84: 'Kinyarwanda',
        85: 'Kirghiz',
        86: 'Komi',
        87: 'Kongo',
        88: 'Korean',
        89: 'Kuanyama',
        90: 'Kurdish',
        91: 'Lao',
        92: 'Latin (Classical)',
        93: 'Latvian',
        94: 'Limburgan',
        95: 'Lingala',
        96: 'Lithuanian',
        97: 'Luba-Katanga',
        98: 'Luganda',
        99: 'Luxembourgish',
        100: 'Macedonian',
        101: 'Magahi',
        102: 'Maithili',
        103: 'Malagasy',
        104: 'Malay',
        105: 'Malayalam',
        106: 'Maltese',
        107: 'Manx',
        108: 'Maori',
        109: 'Marathi',
        110: 'Marshallese',
        111: 'Mongolian',
        112: 'Nauru',
        113: 'Navajo',
        114: 'Ndonga',
        115: 'Nepali',
        116: 'North Ndebele',
        117: 'Northern Sami\'',
        118: 'Norwegian',
        119: 'Occitan',
        120: 'Ojibwa',
        121: 'Oriya',
        122: 'Oromo',
        123: 'Ossetian',
        124: 'Pali',
        125: 'Panjabi, Punjabi',
        126: 'Persian',
        127: 'Polish',
        128: 'Portugese',
        129: 'Pushto',
        130: 'Quechua',
        131: 'Romanian, Moldavian, Moldovan',
        132: 'Romansh',
        133: 'Rundi',
        134: 'Russian',
        135: 'Samoan',
        136: 'Sango',
        137: 'Sanskrit',
        138: 'Sardinian',
        139: 'Serbian',
        140: 'Shona',
        141: 'Sichuan Yi',
        142: 'Sindhi',
        143: 'Sinhala',
        144: 'Slovak',
        145: 'Slovene',
        146: 'Somali',
        147: 'Sotho, Southern',
        148: 'South Ndebele',
        149: 'Spanish',
        150: 'Sundanese',
        151: 'Swahili',
        152:'Swati',
        153: 'Swedish',
        154: 'Tagalog',
        155: 'Tahitian',
        156: 'Tajik',
        157: 'Tamil',
        158: 'Tatar',
        159: 'Telugu',
        160: 'Thai',
        161: 'Tibetian',
        162: 'Tigrinya',
        163: 'Tonga (Tonga Islands)',
        164: 'Tsonga',
        165: 'Tswana',
        166: 'Turkish',
        167: 'Turkmen',
        168: 'Twi',
        169: 'Uighur',
        170: 'Ukrainian',
        171: 'Urdu',
        172: 'Uzbek',
        173: 'Venda',
        174: 'Vietnamese',
        175: 'Walloon',
        176: 'Welsh',
        177: 'Western Frisian'

    }
};